# https://taskfile.dev
version: '3'
vars:
  BINFILE: gitlab-issue-report
  IMG: sgaunet/gitlab-issue-report:latest

tasks:
  default:
    cmds:
      - go mod download
      - CGO_ENABLED=0 go build .
      - upx ./{{.BINFILE}}
    # silent: true
    sources:
    - ./**/*
    method: checksum
    generates:
      - "{{.BINFILE}}"

  install-prereq:
    cmds:
      - go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
      - go install github.com/go-critic/go-critic/cmd/gocritic@latest
      - go install golang.org/x/tools/cmd/goimports@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install github.com/kisielk/errcheck@latest
      - go install honnef.co/go/tools/cmd/staticcheck@latest
      - go install github.com/google/osv-scanner/cmd/osv-scanner@v1
      - go install golang.org/x/vuln/cmd/govulncheck@latest

  # install hooks
  install-pre-commit:
    cmds:
      - pre-commit install

  pre-commit:
    cmds:
      - pre-commit run --all-files

  image:
    deps: 
    - default
    sources:
      - ./**/*
    cmds:
      - docker build . -t {{.IMG}}
      - docker push {{.IMG}}

  snapshot:
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean