# https://taskfile.dev
version: '3'
vars:
  BINFILE: gitlab-issue-report
  IMG: sgaunet/gitlab-issue-report:latest

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task -a

  linter:
    desc: "Run linter"
    cmds:
      # - go generate ./...
      - golangci-lint run

  build:
    desc: "Build the binary"
    cmds:
      - go mod download
      - CGO_ENABLED=0 go build .

  install-prereq:
    desc: "Install pre-requisites"
    cmds:
      - go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
      - go install github.com/go-critic/go-critic/cmd/gocritic@latest
      - go install golang.org/x/tools/cmd/goimports@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install github.com/kisielk/errcheck@latest
      - go install honnef.co/go/tools/cmd/staticcheck@latest
      - go install github.com/google/osv-scanner/cmd/osv-scanner@v1
      - go install golang.org/x/vuln/cmd/govulncheck@latest

  # install hooks
  install-pre-commit:
    desc: "Install pre-commit hooks"
    cmds:
      - pre-commit install

  pre-commit:
    desc: "Run pre-commit hooks on all files"
    cmds:
      - pre-commit run --all-files

  snapshot:
    desc: "Create a snapshot release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    desc: "Create a release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean